#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "dist");
const STATIC_FILES = ["index.html", "style.css", "manifest.json", "sw.js"];
const STATIC_DIRS = ["js"];

function rmDir(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
}

function copyFile(rel) {
  const from = path.join(ROOT, rel);
  const to = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

function copyDir(rel) {
  fs.cpSync(path.join(ROOT, rel), path.join(OUT, rel), { recursive: true });
}

function normalizeUrl(value) {
  return String(value || "").trim().replace(/\/+$/, "");
}

function writeDeployConfig(onlineUrl) {
  const content = [
    '"use strict";',
    "",
    "// Generated by tools/build-pages.cjs during Pages deployment.",
    "window.EQ21_ONLINE_URL = " + JSON.stringify(onlineUrl) + ";",
    ""
  ].join("\n");
  fs.mkdirSync(path.join(OUT, "js"), { recursive: true });
  fs.writeFileSync(path.join(OUT, "js", "deploy-config.js"), content, "utf8");
}

function buildPages(options) {
  const opts = options || {};
  const onlineUrl = normalizeUrl(Object.prototype.hasOwnProperty.call(opts, "onlineUrl") ? opts.onlineUrl : process.env.EQ21_ONLINE_URL);

  rmDir(OUT);
  fs.mkdirSync(OUT, { recursive: true });
  for (const file of STATIC_FILES) copyFile(file);
  for (const dir of STATIC_DIRS) copyDir(dir);
  writeDeployConfig(onlineUrl);

  if (!opts.quiet) {
    console.log("Built Cloudflare Pages static site in dist/");
    console.log("EQ21_ONLINE_URL=" + (onlineUrl || "(fallback)"));
  }
  return { outDir: OUT, onlineUrl };
}

if (require.main === module) buildPages();

module.exports = { buildPages, normalizeUrl };
